name: flutter_carification_app
description: A mobile app for graduate work

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^6.0.5
  flutter_svg: ^2.0.4
  shared_preferences: ^2.1.0
  blurrycontainer: ^1.0.2
  camera: ^0.10.3+2
  path_provider: ^2.0.14
  path: ^1.8.2
  image_picker: ^0.8.7+1
  http: ^0.13.5
  objectbox: ^2.0.0
  objectbox_flutter_libs: any
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  carousel_slider: ^4.2.1
  carousel_indicator: ^1.0.6
  after_layout: ^1.2.0
  dio: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^6.0.3
  build_runner: ^2.3.3
  objectbox_generator: any
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#12252E"
  image: "assets/app_icon.png"
  android_12:
    image: assets/app_icon.png
  fullscreen: true


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/onboarding/
    - assets/icon/
    - assets/test/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter.ttf
